apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "webdb"
---
# criação do service para export a porta internamente ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 10
  selector: #criando o pod
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers: #criando a imagem
        - name: web
          image: adilsonoj/kubernets-web:v2
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
# criação do service para expor a porta externamente NodePort
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
